image: syntacticsugarglider/vessels

check:
  script:
    - cargo check
    - cargo web check

docs:
  stage: deploy
  script:
    - cargo rustdoc
    - rm -rf public
    - mv target/doc/ public
  artifacts:
    paths:
      - public
