[package]
name = "valuedev"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[workspace]
members = [".", "./derive"]

[features]
cbor = ["serde_cbor"]
json = ["serde_json"]
bincode = ["serde_bincode"]
default = ["cbor", "json", "bincode"]

[dependencies]
futures = "0.1.29"
serde = { version = "1.0.101", features = ["derive"] }
failure = "0.1.5"
tokio = "0.1.22"
erased-serde = "0.3.9"
inventory = "0.1.4"
serde_json = { version = "1.0.41", optional = true }
serde_cbor = { version = "0.10.2", optional = true }
serde_bincode = {version = "1.2.0", optional = true, package = "bincode" }

[dependencies.derive]
version = "0.1.0"
path = "./derive"
