[package]
name = "vitruvia"
version = "0.1.0"
authors = ["Jacob Swart", "Tyler Poon"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.13"
serde_derive = "1.0.84"
stdweb-derive = "0.5.1"
serde = "1.0.84"

[target.asmjs-unknown-emscripten.dependencies]
stdweb = "0.4.13"
serde_derive = "1.0.84"
stdweb-derive = "0.5.1"
serde = "1.0.84"

[target.wasm32-unknown-emscripten.dependencies]
stdweb = "0.4.13"
serde_derive = "1.0.84"
stdweb-derive = "0.5.1"
serde = "1.0.84"

[dependencies]
stdweb = { version = "0.4.13", optional = true }
serde = { version = "1.0.84", optional = true }
serde_derive = { version = "1.0.84", optional = true }
stdweb-derive = { version = "0.5.1", optional = true }
failure = { version="0.1.5" }

[profile.release]
lto = true

[features]
check = ["stdweb", "serde", "serde_derive", "stdweb-derive"]
