[package]
authors = ["Izzy Swart", "Tyler Poon"]
edition = "2018"
name = "vitruvia"
version = "0.1.0"

[dependencies]
failure = "0.1.5"
crossbeam-channel = "0.3.8"
futures = "0.1.27"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.13"
serde_derive = "1.0.84"
stdweb-derive = "0.5.1"
serde = "1.0.84"
itertools = "0.8.0"

[target.asmjs-unknown-emscripten.dependencies]
serde = "1.0.84"
serde_derive = "1.0.84"
stdweb = "0.4.13"
stdweb-derive = "0.5.1"
itertools = "0.8.0"

[target.wasm32-unknown-emscripten.dependencies]
serde = "1.0.84"
serde_derive = "1.0.84"
stdweb = "0.4.13"
stdweb-derive = "0.5.1"
itertools = "0.8.0"

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dependencies]
glutin = "0.20.0"
cairo-rs = "0.6.0"
gl = "0.11.0"
glib = "0.7.1"
lcms2 = "5.1.3"
libc = "0.2.54"
pangocairo = "0.7.0"
cairo-sys-rs = "0.8.0"
pango = "0.6.0"
itertools = "0.8.0"
ws = "0.8.1"
tokio = "0.1.21"

[profile.release]
lto = true
debug = false

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"
