[package]
authors = ["Izzy Swart", "Tyler Poon"]
edition = "2018"
name = "vitruvia"
version = "0.1.0"
[dependencies]
failure = "0.1.5"

[profile]
[profile.release]
debug = false
lto = true

[target]
[target.asmjs-unknown-emscripten]
[target.asmjs-unknown-emscripten.dependencies]
serde = "1.0.84"
serde_derive = "1.0.84"
stdweb = "0.4.13"
stdweb-derive = "0.5.1"

[target.wasm32-unknown-emscripten]
[target.wasm32-unknown-emscripten.dependencies]
serde = "1.0.84"
serde_derive = "1.0.84"
stdweb = "0.4.13"
stdweb-derive = "0.5.1"

[target.wasm32-unknown-unknown]
[target.wasm32-unknown-unknown.dependencies]
serde = "1.0.84"
serde_derive = "1.0.84"
stdweb = "0.4.13"
stdweb-derive = "0.5.1"

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dependencies]
glutin = "0.20.0"
cairo-rs = "0.6.0"
gl = "0.11.0"
glib = "0.7.1"