[package]
name = "vitruvia"
version = "0.1.0"
authors = ["Jacob Swart", "Tyler Poon"]
edition = "2018"

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4.13"
serde_derive = "1.0.84"
stdweb-derive = "0.5.1"
serde = "1.0.84"

[target.asmjs-unknown-emscripten.dependencies]
stdweb = "0.4.13"
serde_derive = "1.0.84"
stdweb-derive = "0.5.1"
serde = "1.0.84"

[target.wasm32-unknown-emscripten.dependencies]
stdweb = "0.4.13"
serde_derive = "1.0.84"
stdweb-derive = "0.5.1"
serde = "1.0.84"

[dependencies]
failure = "0.1.5"

[profile.release]
lto = true
debug = false
panic = 'abort'