[package]
name = "vitruvia"
version = "0.1.0"
authors = ["Jacob Swart", "Tyler Poon"]
edition = "2018"

[dependencies]
stdweb = { version = "0.4.13", optional = true }
serde = { version = "1.0.84", optional = true }
serde_derive = { version = "1.0.84", optional = true }
stdweb-derive = { version = "0.5.1", optional = true }

[features]
check = ["stdweb", "serde", "serde_derive", "stdweb-derive"]
