[package]
name = "derive"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.5", features = ["full"] }
proc-macro2 = "1.0.5"
quote = "1.0.2"
lazy_static = "1.4.0"
