[package]
name = "test_vessel"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
vessels = { path = "../../" }
serde = { version = "1.0.101", features = ["derive"] }
futures = "0.3.1"
